// This file is generated by Slice Machine. Update with care!

import CardSwitchComponent from './CardSwitchComponent'

export { CardSwitchComponent }

export const components = {
  card_switch_component: CardSwitchComponent,
}
