// This file is generated by Slice Machine. Update with care!

import CardSwitchComponent from './CardSwitchComponent'
import FirstSlice from './FirstSlice'

export { CardSwitchComponent, FirstSlice }

export const components = {
  card_switch_component: CardSwitchComponent,
  first_slice: FirstSlice,
}
